// How to send HTML files to the client
// How to send/serve static files to the client

const express = require('express');
const path = require('path'); // built-in module
const app = express();

app.use(express.static(path.join(__dirname,'static'))); // this is will return middleware, so we should run this middleware for each route
// to avoid applying many codes for each requests of routes


app.get('/', (req, res) => {
   // res.sendFile(__dirname + '/views/index.html');
   // you have two options to send the file
   
   // either using the absolute path
   // or using the relative path from root directory
   

   // How to get relative path from root directory
   // `__dirname` is the absolute path of the current directory
   // `process.cwd()` is the absolute path of the root directory

   // There another Porblem with paths!
   // Windows uses backslash `\` as a path separator
   // Linux and Mac uses forward slash `/` as a path separator
   // So we need to use `path` module to get the correct path
   // `path.join()` will join the path segments using the correct separator
   // `path.resolve()` will resolve the path segments into an absolute path

   // `path.join()` example
   // path.join('foo', 'bar', 'baz/asdf', 'quux', '..')
   // returns: 'foo/bar/baz/asdf'

   // behind the scenes
   // path modules uses the header `process.platform` to determine the OS
   // or header `User-Agent` in the request to determine the OS (No)
   // it uses OS of the server not the client

   res.sendFile(path.join(process.cwd(), 'views', 'index.html'));
})
 
// when we send HTMLfiles to the client, this html files may contains some other urls for images, css, js, etc
// and the browser will try to get these files from the same url
// and of course, you won't do `app.get()` for each file
// we will use something called 'static files'
// static files are files that are not generated by the server
// they are just files that are stored in the server
// and the server just sends them to the client
// when browser ask server some static files, we want server get these files, it will get them from static folder

// so we need to tell the browser to get these files from the root directory
// we can do this by adding a middleware
// `express.static()` is a middleware that serves static files

app.listen(3000, ()=> console.log('Server is running on port 3000'));